spring.application.name=MockInterviewScheduler

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_APP_EMAIL@gmail.com
spring.mail.password=YOUR_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# mock flag is set to true to skip actual sending during development
app.mail.mock=true
app.mail.from=mock-interview-scheduler@gmail.com

# jwt values
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
